"""Initial migration

Revision ID: ac905a2236dc
Revises: 
Create Date: 2024-12-01 01:30:20.788906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac905a2236dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('golinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortlink', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('golinks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_golinks_shortlink'), ['shortlink'], unique=True)

    op.create_table('link_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortlink', sa.String(length=255), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.Column('args', sa.String(length=1024), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_usage_shortlink'), ['shortlink'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_usage_shortlink'))

    op.drop_table('link_usage')
    with op.batch_alter_table('golinks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_golinks_shortlink'))

    op.drop_table('golinks')
    # ### end Alembic commands ###
